[ERROR] 2015-08-04 23:04:51,111 method:com.newland.bg.commontools.db.DBPool.getConn(DBPool.java:91)
java.sql.SQLException: Connections could not be acquired from the underlying database!
java.sql.SQLException: Connections could not be acquired from the underlying database!
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:106)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:529)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:128)
	at com.newland.bg.commontools.db.DBPool.getConn(DBPool.java:86)
	at com.newland.bg.commontools.db.DBPool.getConn(DBPool.java:80)
	at com.newland.bg.commontools.db.JDBCUtil.getConn(JDBCUtil.java:78)
	at com.newland.bg.commontools.db.JDBCUtil.beginTransection(JDBCUtil.java:499)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:382)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: com.mchange.v2.resourcepool.CannotAcquireResourceException: A ResourcePool could not acquire a resource from its primary factory or source.
	at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1319)
	at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:557)
	at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:477)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:525)
	... 9 more
[ERROR] 2015-08-04 23:04:51,116 method:com.newland.bg.commontools.db.JDBCUtil.getConn(JDBCUtil.java:82)
java.lang.RuntimeException: 无法从数据源获取连接 
java.lang.RuntimeException: 无法从数据源获取连接 
	at com.newland.bg.commontools.db.DBPool.getConn(DBPool.java:92)
	at com.newland.bg.commontools.db.DBPool.getConn(DBPool.java:80)
	at com.newland.bg.commontools.db.JDBCUtil.getConn(JDBCUtil.java:78)
	at com.newland.bg.commontools.db.JDBCUtil.beginTransection(JDBCUtil.java:499)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:382)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Connections could not be acquired from the underlying database!
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:106)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:529)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:128)
	at com.newland.bg.commontools.db.DBPool.getConn(DBPool.java:86)
	... 7 more
Caused by: com.mchange.v2.resourcepool.CannotAcquireResourceException: A ResourcePool could not acquire a resource from its primary factory or source.
	at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1319)
	at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:557)
	at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:477)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:525)
	... 9 more
[ERROR] 2015-08-04 23:04:51,117 method:com.newland.bg.commontools.db.JDBCUtil.beginTransection(JDBCUtil.java:505)
java.lang.NullPointerException
java.lang.NullPointerException
	at com.newland.bg.commontools.db.JDBCUtil.beginTransection(JDBCUtil.java:501)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:382)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
[ERROR] 2015-08-04 23:04:51,196 method:com.newland.bg.commontools.db.DBPool.getConn(DBPool.java:91)
java.sql.SQLException: Connections could not be acquired from the underlying database!
java.sql.SQLException: Connections could not be acquired from the underlying database!
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:106)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:529)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:128)
	at com.newland.bg.commontools.db.DBPool.getConn(DBPool.java:86)
	at com.newland.bg.commontools.db.DBPool.getConn(DBPool.java:80)
	at com.newland.bg.commontools.db.JDBCUtil.getConn(JDBCUtil.java:78)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:388)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: com.mchange.v2.resourcepool.CannotAcquireResourceException: A ResourcePool could not acquire a resource from its primary factory or source.
	at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1319)
	at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:557)
	at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:477)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:525)
	... 8 more
[ERROR] 2015-08-04 23:04:51,197 method:com.newland.bg.commontools.db.JDBCUtil.getConn(JDBCUtil.java:82)
java.lang.RuntimeException: 无法从数据源获取连接 
java.lang.RuntimeException: 无法从数据源获取连接 
	at com.newland.bg.commontools.db.DBPool.getConn(DBPool.java:92)
	at com.newland.bg.commontools.db.DBPool.getConn(DBPool.java:80)
	at com.newland.bg.commontools.db.JDBCUtil.getConn(JDBCUtil.java:78)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:388)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Connections could not be acquired from the underlying database!
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:106)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:529)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:128)
	at com.newland.bg.commontools.db.DBPool.getConn(DBPool.java:86)
	... 6 more
Caused by: com.mchange.v2.resourcepool.CannotAcquireResourceException: A ResourcePool could not acquire a resource from its primary factory or source.
	at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1319)
	at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:557)
	at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:477)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:525)
	... 8 more
[ERROR] 2015-08-04 23:04:51,762 method:com.newland.bg.commontools.db.DBPool.getConn(DBPool.java:91)
java.sql.SQLException: Connections could not be acquired from the underlying database!
java.sql.SQLException: Connections could not be acquired from the underlying database!
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:106)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:529)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:128)
	at com.newland.bg.commontools.db.DBPool.getConn(DBPool.java:86)
	at com.newland.bg.commontools.db.DBPool.getConn(DBPool.java:80)
	at com.newland.bg.commontools.db.JDBCUtil.getConn(JDBCUtil.java:78)
	at com.newland.bg.commontools.db.JDBCUtil.rollBack(JDBCUtil.java:542)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:402)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: com.mchange.v2.resourcepool.CannotAcquireResourceException: A ResourcePool could not acquire a resource from its primary factory or source.
	at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1319)
	at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:557)
	at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:477)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:525)
	... 9 more
[ERROR] 2015-08-04 23:04:51,764 method:com.newland.bg.commontools.db.JDBCUtil.getConn(JDBCUtil.java:82)
java.lang.RuntimeException: 无法从数据源获取连接 
java.lang.RuntimeException: 无法从数据源获取连接 
	at com.newland.bg.commontools.db.DBPool.getConn(DBPool.java:92)
	at com.newland.bg.commontools.db.DBPool.getConn(DBPool.java:80)
	at com.newland.bg.commontools.db.JDBCUtil.getConn(JDBCUtil.java:78)
	at com.newland.bg.commontools.db.JDBCUtil.rollBack(JDBCUtil.java:542)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:402)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Connections could not be acquired from the underlying database!
	at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:106)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:529)
	at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:128)
	at com.newland.bg.commontools.db.DBPool.getConn(DBPool.java:86)
	... 7 more
Caused by: com.mchange.v2.resourcepool.CannotAcquireResourceException: A ResourcePool could not acquire a resource from its primary factory or source.
	at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1319)
	at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:557)
	at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:477)
	at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:525)
	... 9 more
[ERROR] 2015-08-04 23:04:51,764 method:com.newland.bg.commontools.db.JDBCUtil.rollBack(JDBCUtil.java:548)
java.lang.NullPointerException
java.lang.NullPointerException
	at com.newland.bg.commontools.db.JDBCUtil.rollBack(JDBCUtil.java:544)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:402)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
[ERROR] 2015-08-04 23:04:51,765 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:22)
java.lang.Exception: java.lang.NullPointerException
SQL:insert into iTask_tag(id, content, create_time) values(1, '工作', 1402017888889)
java.lang.Exception: java.lang.NullPointerException
SQL:insert into iTask_tag(id, content, create_time) values(1, '工作', 1402017888889)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:403)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.lang.NullPointerException
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:390)
	... 3 more
[ERROR] 2015-08-04 23:05:38,773 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Field 'user_id' doesn't have a default value
SQL:insert into iTask_tag(id, content, create_time) values(1, '工作', 1402017888889)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Field 'user_id' doesn't have a default value
SQL:insert into iTask_tag(id, content, create_time) values(1, '工作', 1402017888889)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Field 'user_id' doesn't have a default value
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2934)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:05:38,944 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Field 'user_id' doesn't have a default value
SQL:insert into iTask_tag(id, content, create_time) values(3, '安卓项目', 1402024268990)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Field 'user_id' doesn't have a default value
SQL:insert into iTask_tag(id, content, create_time) values(3, '安卓项目', 1402024268990)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Field 'user_id' doesn't have a default value
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2934)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:05:39,270 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Field 'user_id' doesn't have a default value
SQL:insert into iTask_tag(id, content, create_time) values(5, '运动', 1402030411067)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Field 'user_id' doesn't have a default value
SQL:insert into iTask_tag(id, content, create_time) values(5, '运动', 1402030411067)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Field 'user_id' doesn't have a default value
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2934)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:05:39,721 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Field 'user_id' doesn't have a default value
SQL:insert into iTask_tag(id, content, create_time) values(6, '学习', 1402030506712)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Field 'user_id' doesn't have a default value
SQL:insert into iTask_tag(id, content, create_time) values(6, '学习', 1402030506712)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Field 'user_id' doesn't have a default value
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2934)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:05:39,964 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Field 'user_id' doesn't have a default value
SQL:insert into iTask_tag(id, content, create_time) values(7, '纸质书', 1402030521000)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Field 'user_id' doesn't have a default value
SQL:insert into iTask_tag(id, content, create_time) values(7, '纸质书', 1402030521000)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Field 'user_id' doesn't have a default value
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2934)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:05:40,199 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Field 'user_id' doesn't have a default value
SQL:insert into iTask_tag(id, content, create_time) values(8, '电子书', 1402030527119)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Field 'user_id' doesn't have a default value
SQL:insert into iTask_tag(id, content, create_time) values(8, '电子书', 1402030527119)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Field 'user_id' doesn't have a default value
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2934)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:05:40,786 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Field 'user_id' doesn't have a default value
SQL:insert into iTask_tag(id, content, create_time) values(9, '成长', 1406764942747)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Field 'user_id' doesn't have a default value
SQL:insert into iTask_tag(id, content, create_time) values(9, '成长', 1406764942747)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Field 'user_id' doesn't have a default value
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2934)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:05:41,019 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Field 'user_id' doesn't have a default value
SQL:insert into iTask_tag(id, content, create_time) values(10, '待办事项', 1406781408484)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Field 'user_id' doesn't have a default value
SQL:insert into iTask_tag(id, content, create_time) values(10, '待办事项', 1406781408484)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Field 'user_id' doesn't have a default value
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2934)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:05:41,323 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Field 'user_id' doesn't have a default value
SQL:insert into iTask_tag(id, content, create_time) values(11, '有声小说', 1407322766502)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Field 'user_id' doesn't have a default value
SQL:insert into iTask_tag(id, content, create_time) values(11, '有声小说', 1407322766502)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Field 'user_id' doesn't have a default value
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2934)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:05:41,768 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Field 'user_id' doesn't have a default value
SQL:insert into iTask_tag(id, content, create_time) values(12, '其他项目', 1410241734992)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Field 'user_id' doesn't have a default value
SQL:insert into iTask_tag(id, content, create_time) values(12, '其他项目', 1410241734992)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Field 'user_id' doesn't have a default value
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2934)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:05:42,005 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Field 'user_id' doesn't have a default value
SQL:insert into iTask_tag(id, content, create_time) values(13, '纪录片', 1410325001136)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Field 'user_id' doesn't have a default value
SQL:insert into iTask_tag(id, content, create_time) values(13, '纪录片', 1410325001136)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Field 'user_id' doesn't have a default value
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2934)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:05:42,452 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Field 'user_id' doesn't have a default value
SQL:insert into iTask_tag(id, content, create_time) values(14, '结婚相关', 1411296882815)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Field 'user_id' doesn't have a default value
SQL:insert into iTask_tag(id, content, create_time) values(14, '结婚相关', 1411296882815)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Field 'user_id' doesn't have a default value
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2934)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:05:42,690 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Field 'user_id' doesn't have a default value
SQL:insert into iTask_tag(id, content, create_time) values(15, '公开课', 1411706103510)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Field 'user_id' doesn't have a default value
SQL:insert into iTask_tag(id, content, create_time) values(15, '公开课', 1411706103510)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Field 'user_id' doesn't have a default value
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2934)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:09:07,575 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1402017888889' for column 'create_time' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(1, '工作', 1402017888889, '')
com.newland.bg.commontools.exception.NewlandSQLException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1402017888889' for column 'create_time' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(1, '工作', 1402017888889, '')
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1402017888889' for column 'create_time' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2932)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:09:07,796 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1402024268990' for column 'create_time' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(3, '安卓项目', 1402024268990, '')
com.newland.bg.commontools.exception.NewlandSQLException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1402024268990' for column 'create_time' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(3, '安卓项目', 1402024268990, '')
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1402024268990' for column 'create_time' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2932)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:09:08,338 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1402030411067' for column 'create_time' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(5, '运动', 1402030411067, '')
com.newland.bg.commontools.exception.NewlandSQLException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1402030411067' for column 'create_time' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(5, '运动', 1402030411067, '')
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1402030411067' for column 'create_time' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2932)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:09:08,645 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1402030506712' for column 'create_time' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(6, '学习', 1402030506712, '')
com.newland.bg.commontools.exception.NewlandSQLException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1402030506712' for column 'create_time' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(6, '学习', 1402030506712, '')
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1402030506712' for column 'create_time' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2932)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:09:08,894 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1402030521000' for column 'create_time' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(7, '纸质书', 1402030521000, '')
com.newland.bg.commontools.exception.NewlandSQLException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1402030521000' for column 'create_time' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(7, '纸质书', 1402030521000, '')
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1402030521000' for column 'create_time' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2932)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:09:09,507 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1402030527119' for column 'create_time' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(8, '电子书', 1402030527119, '')
com.newland.bg.commontools.exception.NewlandSQLException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1402030527119' for column 'create_time' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(8, '电子书', 1402030527119, '')
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1402030527119' for column 'create_time' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2932)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:09:09,661 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1406764942747' for column 'create_time' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(9, '成长', 1406764942747, '')
com.newland.bg.commontools.exception.NewlandSQLException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1406764942747' for column 'create_time' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(9, '成长', 1406764942747, '')
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1406764942747' for column 'create_time' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2932)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:09:09,807 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1406781408484' for column 'create_time' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(10, '待办事项', 1406781408484, '')
com.newland.bg.commontools.exception.NewlandSQLException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1406781408484' for column 'create_time' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(10, '待办事项', 1406781408484, '')
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1406781408484' for column 'create_time' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2932)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:09:09,968 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1407322766502' for column 'create_time' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(11, '有声小说', 1407322766502, '')
com.newland.bg.commontools.exception.NewlandSQLException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1407322766502' for column 'create_time' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(11, '有声小说', 1407322766502, '')
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1407322766502' for column 'create_time' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2932)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:09:10,114 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1410241734992' for column 'create_time' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(12, '其他项目', 1410241734992, '')
com.newland.bg.commontools.exception.NewlandSQLException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1410241734992' for column 'create_time' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(12, '其他项目', 1410241734992, '')
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1410241734992' for column 'create_time' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2932)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:09:10,267 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(13, '纪录片', 1410325001136, '')
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(13, '纪录片', 1410325001136, '')
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2934)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:09:10,425 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1411296882815' for column 'create_time' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(14, '结婚相关', 1411296882815, '')
com.newland.bg.commontools.exception.NewlandSQLException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1411296882815' for column 'create_time' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(14, '结婚相关', 1411296882815, '')
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1411296882815' for column 'create_time' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2932)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:09:10,654 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1411706103510' for column 'create_time' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(15, '公开课', 1411706103510, '')
com.newland.bg.commontools.exception.NewlandSQLException: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1411706103510' for column 'create_time' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(15, '公开课', 1411706103510, '')
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1411706103510' for column 'create_time' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2932)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:11:20,702 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(1, '工作', 1402017888889, '')
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(1, '工作', 1402017888889, '')
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2934)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:11:20,854 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(3, '安卓项目', 1402024268990, '')
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(3, '安卓项目', 1402024268990, '')
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2934)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:11:21,003 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(5, '运动', 1402030411067, '')
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(5, '运动', 1402030411067, '')
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2934)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:11:21,175 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(6, '学习', 1402030506712, '')
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(6, '学习', 1402030506712, '')
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2934)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:11:21,314 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(7, '纸质书', 1402030521000, '')
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(7, '纸质书', 1402030521000, '')
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2934)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:11:21,462 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(8, '电子书', 1402030527119, '')
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(8, '电子书', 1402030527119, '')
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2934)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:11:21,608 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(9, '成长', 1406764942747, '')
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(9, '成长', 1406764942747, '')
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2934)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:11:22,096 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(10, '待办事项', 1406781408484, '')
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(10, '待办事项', 1406781408484, '')
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2934)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:11:22,490 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(11, '有声小说', 1407322766502, '')
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(11, '有声小说', 1407322766502, '')
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2934)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:11:22,728 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(12, '其他项目', 1410241734992, '')
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(12, '其他项目', 1410241734992, '')
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2934)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:11:22,956 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(13, '纪录片', 1410325001136, '')
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(13, '纪录片', 1410325001136, '')
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2934)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:11:23,259 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(14, '结婚相关', 1411296882815, '')
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(14, '结婚相关', 1411296882815, '')
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2934)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:11:23,509 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(15, '公开课', 1411706103510, '')
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(15, '公开课', 1411706103510, '')
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Incorrect integer value: '' for column 'user_id' at row 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2934)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:11:34,999 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: 'lynn' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(1, '工作', 1402017888889, 'lynn')
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: 'lynn' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(1, '工作', 1402017888889, 'lynn')
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Incorrect integer value: 'lynn' for column 'user_id' at row 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2934)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:11:35,147 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: 'lynn' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(3, '安卓项目', 1402024268990, 'lynn')
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: 'lynn' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(3, '安卓项目', 1402024268990, 'lynn')
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Incorrect integer value: 'lynn' for column 'user_id' at row 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2934)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:11:35,342 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: 'lynn' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(5, '运动', 1402030411067, 'lynn')
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: 'lynn' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(5, '运动', 1402030411067, 'lynn')
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Incorrect integer value: 'lynn' for column 'user_id' at row 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2934)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:11:35,500 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: 'lynn' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(6, '学习', 1402030506712, 'lynn')
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: 'lynn' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(6, '学习', 1402030506712, 'lynn')
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Incorrect integer value: 'lynn' for column 'user_id' at row 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2934)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:11:35,690 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: 'lynn' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(7, '纸质书', 1402030521000, 'lynn')
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: 'lynn' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(7, '纸质书', 1402030521000, 'lynn')
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Incorrect integer value: 'lynn' for column 'user_id' at row 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2934)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:11:35,845 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: 'lynn' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(8, '电子书', 1402030527119, 'lynn')
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: 'lynn' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(8, '电子书', 1402030527119, 'lynn')
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Incorrect integer value: 'lynn' for column 'user_id' at row 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2934)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:11:35,997 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: 'lynn' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(9, '成长', 1406764942747, 'lynn')
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: 'lynn' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(9, '成长', 1406764942747, 'lynn')
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Incorrect integer value: 'lynn' for column 'user_id' at row 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2934)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:11:36,143 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: 'lynn' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(10, '待办事项', 1406781408484, 'lynn')
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: 'lynn' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(10, '待办事项', 1406781408484, 'lynn')
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Incorrect integer value: 'lynn' for column 'user_id' at row 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2934)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:11:36,322 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: 'lynn' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(11, '有声小说', 1407322766502, 'lynn')
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: 'lynn' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(11, '有声小说', 1407322766502, 'lynn')
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Incorrect integer value: 'lynn' for column 'user_id' at row 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2934)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:11:36,473 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: 'lynn' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(12, '其他项目', 1410241734992, 'lynn')
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: 'lynn' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(12, '其他项目', 1410241734992, 'lynn')
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Incorrect integer value: 'lynn' for column 'user_id' at row 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2934)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:11:36,640 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: 'lynn' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(13, '纪录片', 1410325001136, 'lynn')
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: 'lynn' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(13, '纪录片', 1410325001136, 'lynn')
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Incorrect integer value: 'lynn' for column 'user_id' at row 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2934)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:11:36,785 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: 'lynn' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(14, '结婚相关', 1411296882815, 'lynn')
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: 'lynn' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(14, '结婚相关', 1411296882815, 'lynn')
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Incorrect integer value: 'lynn' for column 'user_id' at row 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2934)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
[ERROR] 2015-08-04 23:11:36,932 method:com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:20)
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: 'lynn' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(15, '公开课', 1411706103510, 'lynn')
com.newland.bg.commontools.exception.NewlandSQLException: java.sql.SQLException: Incorrect integer value: 'lynn' for column 'user_id' at row 1
SQL:insert into iTask_tag(id, content, create_time, user_id) values(15, '公开课', 1411706103510, 'lynn')
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:400)
	at com.lynn.iTaskServer.dao.TaskDao.saveTag(TaskDao.java:18)
	at com.lynn.iTaskServer.core.TaskServer.task(TaskServer.java:38)
	at com.lynn.iTaskServer.core.TaskServer.main(TaskServer.java:78)
Caused by: java.sql.SQLException: Incorrect integer value: 'lynn' for column 'user_id' at row 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2934)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1616)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:1708)
	at com.mysql.jdbc.Connection.execSQL(Connection.java:3255)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1293)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1566)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1480)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1465)
	at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.executeUpdate(NewProxyPreparedStatement.java:105)
	at com.newland.bg.commontools.db.JDBCUtil.execute(JDBCUtil.java:396)
	... 3 more
